// import * as THREE from 'three';
// import { useGLTF } from '@react-three/drei'
// import React, { useRef, useState } from 'react'
// import { Canvas, useFrame } from '@react-three/fiber'
// //import { Model } from './model' 

// const scene = new THREE.Scene();
// const camera = new THREE.PerspectiveCamera(75, window.innerHeight / window.innerHeight, 0.1, 1000);
// const light = new THREE.AmbientLight(0x404040);
// const renderer = new THREE.WebGLRenderer();
// renderer.setSize( window.innerWidth, window.innerHeight );
// document.body.appendChild( renderer.domElement );
// const geometry = new THREE.BoxGeometry( 1, 1, 1 );
// const material = new THREE.MeshBasicMaterial( { color: 0x00ff00 });


// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// export function Model(props) {
//   const { nodes, materials } = useGLTF('/GiftBox.gltf')
//   useFrame(() => (scene.rotateY =scroll.offset * Math.PI)) 
//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         geometry={nodes.Giftbox01.geometry}
//         material={materials.Pink01}
//         position={[0, 1.1, 0]}
//         userData={{ name: 'Giftbox01' }}
//       />
//       <mesh
//         geometry={nodes.Giftbox02.geometry}
//         material={materials.Pink02}
//         position={[0, 1.3, 0]}
//         rotation={[0, Math.PI / 2, 0]}
//         userData={{ name: 'Giftbox02' }}
//       />
//       <mesh
//         geometry={nodes.Giftbox03.geometry}
//         material={materials.Pink02}
//         position={[0, 2.2, 0]}
//         rotation={[0, -Math.PI / 4, 0]}
//         userData={{ name: 'Giftbox03' }}
//       />
//       <mesh
//         geometry={nodes.Giftbox04.geometry}
//         material={materials.Pink03}
//         position={[0, 2.2, 0]}
//         rotation={[-0.1, 0, 0]}
//         scale={[0.2, 0.4, 0.4]}
//         userData={{ name: 'Giftbox04' }}
//       />
//       <mesh
//         geometry={nodes.Giftbox05.geometry}
//         material={materials.Pink01}
//         position={[0, 2.2, 0]}
//         userData={{ name: 'Giftbox05' }}
//       />
//       <mesh
//         geometry={nodes.Giftbox06.geometry}
//         material={materials.Yellow01}
//         position={[0, 2.4, 0]}
//         scale={0.2}
//         userData={{ name: 'Giftbox06' }}
//       />
//     </group>
//   )
// }




// const Home = () => {
//   return (

//     <section className="w-full h-screen relative">
//       <div className='absolute top-28 left-0 right-0 z-10 flex items-center justify-center'>

//       <Canvas>
//         <ambientLight intensity={Math.PI / 2} />
//         <spotLight position={[10, 10, 10]} angle={0.15} penumbra={1} decay={0} intensity={Math.PI} />
//         <pointLight position={[-10, -10, -10]} decay={0} intensity={Math.PI} />
//         <Model />
//       </Canvas>
    

//       </div>
//     </section>
//   )

//   }

//export default Home


import React from 'react'




function Home() {
  return (
    <div>
      <p>Hello world how are you i am a tea pot</p>


    </div>
  );
}

export default Home